project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - docs/*.qmd
  resources:
    - docs/assets/**

website:
  title: "KRISS Keyword Pipeline Report"
  description: "Final report and operational handbook for the KRISS standard-research analytics program"
  repo-url: https://github.com/kimyoungjin06/final-report-placeholder
  repo-actions: [source, issue]
  navbar:
    left:
      - text: "문서 안내 / Document Guide"
        menu:
          - text: "홈 / Home"
            href: index.qmd
          - text: "프로젝트 개요"
            href: docs/research_overview.qmd
          - text: "추진 전략 & 수행"
            href: docs/strategy_execution.qmd
      - text: "1. 데이터 & 방법론"
        menu:
          - text: "1.1 데이터 구조 & 아이템 체계"
            href: docs/data_architecture.qmd
          - text: "1.2 파이프라인 아키텍처"
            href: docs/pipeline_architecture.qmd
          - text: "1.3 Algorithmic Scoring"
            href: docs/algorithmic_scoring.qmd
          - text: "1.4 Configuration Playbook"
            href: docs/configuration.qmd
      - text: "2. 도메인 연구지형도"
        href: docs/module_domain_map.qmd
      - text: "3. 기관 성과 & 포트폴리오"
        href: docs/module_institutional.qmd
      - text: "4. 운영 & 일정"
        menu:
          - text: "4.1 수행 체계 & 일정"
            href: docs/delivery_plan.qmd
          - text: "4.2 Operations & Restart"
            href: docs/operations.qmd
      - text: "Diagnostics & Appendix"
        menu:
          - text: "Diagnostics"
            href: docs/diagnostics.qmd
          - text: "Appendix"
            href: docs/appendix.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: false
    code-copy: true
