<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>KRISS 표준과학 연구 데이터북 (Book) - Appendix _ — 30-169 - 위상 양자물질 전자구조 측정 (역량 공백)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../docs/detailed_reports/cluster_62/report.html" rel="next">
<link href="../../../docs/detailed_reports/cluster_179/report.html" rel="prev">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="../../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simple-datatables@9.0.0/dist/style.css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@9.0.0" defer=""></script>
<script src="docs/assets/js/datatable-init.js" defer=""></script>
<script>
document.addEventListener("DOMContentLoaded", () => {
  const chapterTitle = document.querySelector("h1.web-chapter-title");
  if (chapterTitle) {
    const titleBlock = document.querySelector(".quarto-title-block");
    if (titleBlock) {
      titleBlock.style.display = "none";
    }

    const chapterNumber =
      chapterTitle.getAttribute("data-number") ||
      (chapterTitle.querySelector(".header-section-number") || {}).textContent?.trim();

    if (chapterNumber) {
      const prefixRegex = /^\s*표[\s\u00A0]*\d+(?:\.\d+)?[\s\u00A0]*:/;
      const tableCaptions = Array.from(
        document.querySelectorAll("figcaption.quarto-float-tbl")
      );

      let tableIndex = 0;
      const tableIds = [];

      tableCaptions.forEach((caption) => {
        tableIndex += 1;
        const newPrefix = `표 ${chapterNumber}.${tableIndex}:`;
        const walker = document.createTreeWalker(caption, NodeFilter.SHOW_TEXT, null);
        const textNode = walker.nextNode();

        if (textNode && prefixRegex.test(textNode.nodeValue)) {
          textNode.nodeValue = textNode.nodeValue.replace(prefixRegex, newPrefix);
        }

        const float = caption.closest(".quarto-float");
        if (float && float.id && float.id.startsWith("tbl-")) {
          tableIds.push(float.id);
        }
      });

      tableIds.forEach((id, idx) => {
        const label = `표 ${chapterNumber}.${idx + 1}`;
        document.querySelectorAll(`a[href="#${id}"]`).forEach((anchor) => {
          const text = (anchor.textContent || "").trim();
          if (/^표[\s\u00A0]*\d+(?:\.\d+)?$/.test(text)) {
            anchor.textContent = label;
          }
        });
      });

      const figPrefixRegex = /^\s*그림[\s\u00A0]*\d+(?:\.\d+)?[\s\u00A0]*:/;
      const figCaptions = Array.from(
        document.querySelectorAll("figure figcaption")
      ).filter((caption) => {
        const figure = caption.closest("figure");
        return !(figure && figure.classList.contains("quarto-float-tbl"));
      });
      let figIndex = 0;
      const figIds = [];

      figCaptions.forEach((caption) => {
        figIndex += 1;
        const newPrefix = `그림 ${chapterNumber}.${figIndex}:`;
        const walker = document.createTreeWalker(caption, NodeFilter.SHOW_TEXT, null);
        let textNode = walker.nextNode();
        while (textNode && !textNode.nodeValue.trim()) {
          textNode = walker.nextNode();
        }

        if (textNode) {
          if (figPrefixRegex.test(textNode.nodeValue)) {
            textNode.nodeValue = textNode.nodeValue.replace(figPrefixRegex, newPrefix);
          } else {
            textNode.nodeValue = `${newPrefix} ${textNode.nodeValue.trim()}`;
          }
        } else {
          caption.prepend(document.createTextNode(`${newPrefix} `));
        }

        const float = caption.closest(".quarto-float");
        if (float && float.id && float.id.startsWith("fig-")) {
          figIds.push(float.id);
        }
      });

      figIds.forEach((id, idx) => {
        const label = `그림 ${chapterNumber}.${idx + 1}`;
        document.querySelectorAll(`a[href="#${id}"]`).forEach((anchor) => {
          const text = (anchor.textContent || "").trim();
          if (/^그림[\s\u00A0]*\d+(?:\.\d+)?$/.test(text)) {
            anchor.textContent = label;
          }
        });
      });
    }
  }

  document.querySelectorAll(".carousel-gallery").forEach((carousel) => {
    const track = carousel.querySelector(".carousel-track");
    const slides = Array.from(carousel.querySelectorAll(".carousel-slide"));
    if (!track || slides.length === 0) {
      return;
    }

    const dotsContainer = carousel.querySelector(".carousel-dots");
    const prevBtn = carousel.querySelector(".carousel-btn.prev");
    const nextBtn = carousel.querySelector(".carousel-btn.next");
    let currentIndex = 0;
    let isPointerDown = false;
    let isDragging = false;
    let startX = 0;
    let startY = 0;
    let dragStartTranslate = 0;
    let hasDragged = false;

    const getSlideWidth = () => {
      const styles = window.getComputedStyle(carousel);
      const paddingLeft = parseFloat(styles.paddingLeft) || 0;
      const paddingRight = parseFloat(styles.paddingRight) || 0;
      return carousel.clientWidth - paddingLeft - paddingRight;
    };

    const updateDots = () => {
      if (!dotsContainer) {
        return;
      }
      dotsContainer.querySelectorAll(".carousel-dot").forEach((dot, idx) => {
        dot.classList.toggle("is-active", idx === currentIndex);
      });
    };

    const update = () => {
      const width = getSlideWidth();
      slides.forEach((slide) => {
        slide.style.width = `${width}px`;
      });
      track.style.transform = `translateX(-${currentIndex * width}px)`;
      updateDots();
    };

    const goTo = (index) => {
      currentIndex = (index + slides.length) % slides.length;
      update();
    };

    if (dotsContainer) {
      dotsContainer.innerHTML = "";
      slides.forEach((_, idx) => {
        const dot = document.createElement("button");
        dot.type = "button";
        dot.className = "carousel-dot";
        dot.setAttribute("aria-label", `슬라이드 ${idx + 1}`);
        dot.addEventListener("click", () => goTo(idx));
        dotsContainer.appendChild(dot);
      });
    }

    if (prevBtn) {
      prevBtn.addEventListener("click", () => goTo(currentIndex - 1));
    }
    if (nextBtn) {
      nextBtn.addEventListener("click", () => goTo(currentIndex + 1));
    }

    track.addEventListener("pointerdown", (event) => {
      if (event.button && event.button !== 0) {
        return;
      }
      isPointerDown = true;
      isDragging = false;
      hasDragged = false;
      startX = event.clientX;
      startY = event.clientY;
      dragStartTranslate = -currentIndex * getSlideWidth();
    });

    track.addEventListener("pointermove", (event) => {
      if (!isPointerDown) {
        return;
      }
      const deltaX = event.clientX - startX;
      const deltaY = event.clientY - startY;
      if (!isDragging) {
        if (Math.abs(deltaX) > 12 && Math.abs(deltaX) > Math.abs(deltaY) + 4) {
          isDragging = true;
          hasDragged = true;
          track.classList.add("is-dragging");
          try {
            track.setPointerCapture(event.pointerId);
          } catch (error) {
            // ignore if pointer capture fails
          }
        } else {
          return;
        }
      }
      track.style.transform = `translateX(${dragStartTranslate + deltaX}px)`;
    });

    const endDrag = (event) => {
      if (!isPointerDown) {
        return;
      }
      isPointerDown = false;
      if (!isDragging) {
        return;
      }
      isDragging = false;
      track.classList.remove("is-dragging");
      try {
        track.releasePointerCapture(event.pointerId);
      } catch (error) {
        // ignore if pointer was not captured
      }
      const delta = event.clientX - startX;
      const width = getSlideWidth();
      if (Math.abs(delta) > width * 0.2) {
        goTo(delta < 0 ? currentIndex + 1 : currentIndex - 1);
      } else {
        update();
      }
      if (hasDragged) {
        track.dataset.dragging = "true";
        window.setTimeout(() => {
          track.dataset.dragging = "false";
        }, 0);
      }
    };

    track.addEventListener("pointerup", endDrag);
    track.addEventListener("pointercancel", endDrag);

    track.addEventListener("click", (event) => {
      if (track.dataset.dragging === "true") {
        event.preventDefault();
        event.stopPropagation();
      }
    });

    window.addEventListener("resize", update);
    update();
  });

  const initLightboxSwipe = () => {
    const supportsFinePointer = window.matchMedia("(pointer: fine)").matches;
    if (!supportsFinePointer) {
      return;
    }

    const container = document.querySelector(".glightbox-container");
    if (!container || container.dataset.swipeInit === "true") {
      return;
    }
    container.dataset.swipeInit = "true";

    const slider = container.querySelector("#glightbox-slider");
    if (!slider) {
      return;
    }

    let isPointerDown = false;
    let isDragging = false;
    let hasDragged = false;
    let startX = 0;
    let startY = 0;

    const isZoomed = () => {
      const active = slider.querySelector(".gslide.current");
      return active && active.classList.contains("zoomed");
    };

    const goNext = () => {
      const nextBtn = container.querySelector(".gnext");
      if (nextBtn && !nextBtn.classList.contains("disabled")) {
        nextBtn.click();
      }
    };

    const goPrev = () => {
      const prevBtn = container.querySelector(".gprev");
      if (prevBtn && !prevBtn.classList.contains("disabled")) {
        prevBtn.click();
      }
    };

    slider.addEventListener("pointerdown", (event) => {
      if (event.button && event.button !== 0) {
        return;
      }
      if (isZoomed()) {
        return;
      }
      if (event.target.closest(".gbtn")) {
        return;
      }
      isPointerDown = true;
      isDragging = false;
      hasDragged = false;
      startX = event.clientX;
      startY = event.clientY;
    });

    slider.addEventListener("pointermove", (event) => {
      if (!isPointerDown) {
        return;
      }
      const deltaX = event.clientX - startX;
      const deltaY = event.clientY - startY;
      if (!isDragging) {
        if (Math.abs(deltaX) > 12 && Math.abs(deltaX) > Math.abs(deltaY) + 4) {
          isDragging = true;
          hasDragged = true;
          slider.classList.add("is-dragging");
          try {
            slider.setPointerCapture(event.pointerId);
          } catch (error) {
            // ignore if pointer capture fails
          }
        } else {
          return;
        }
      }
    });

    const endDrag = (event) => {
      if (!isPointerDown) {
        return;
      }
      isPointerDown = false;
      if (!isDragging) {
        return;
      }
      isDragging = false;
      slider.classList.remove("is-dragging");
      try {
        slider.releasePointerCapture(event.pointerId);
      } catch (error) {
        // ignore if pointer was not captured
      }

      const deltaX = event.clientX - startX;
      const deltaY = event.clientY - startY;
      if (
        hasDragged &&
        Math.abs(deltaX) > Math.abs(deltaY) &&
        Math.abs(deltaX) > 50
      ) {
        if (deltaX < 0) {
          goNext();
        } else {
          goPrev();
        }
      }

      if (hasDragged) {
        slider.dataset.dragging = "true";
        window.setTimeout(() => {
          slider.dataset.dragging = "false";
        }, 0);
      }
    };

    slider.addEventListener("pointerup", endDrag);
    slider.addEventListener("pointercancel", endDrag);

    slider.addEventListener("click", (event) => {
      if (slider.dataset.dragging === "true") {
        event.preventDefault();
        event.stopPropagation();
      }
    });
  };

  initLightboxSwipe();
  const lightboxObserver = new MutationObserver(() => initLightboxSwipe());
  lightboxObserver.observe(document.body, { childList: true, subtree: true });
});
</script>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">KRISS 표준과학 연구 데이터북 (Book)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="https://kisti-globalrnd.github.io/kriss-databook-2025/" aria-current="page"> 
<span class="menu-text">홈 / Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-databook" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">데이터북 / Databook</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-databook">    
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/book/index.html">
 <span class="dropdown-text">서문 / Preface</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/book/part-1-landscape.html">
 <span class="dropdown-text">문헌 집합 및 연구지형도 구축</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/book/part-2-capability.html">
 <span class="dropdown-text">기관 연구역량 진단</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/book/part-3-emerging.html">
 <span class="dropdown-text">유망 연구영역 도출</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">인터랙티브 도구 / Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/keyword_trends.html">
 <span class="dropdown-text">키워드 추세 탐색기 / Keyword Trends</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/vosviewer_explorer.html">
 <span class="dropdown-text">연구지형도(인터랙티브 맵) / VOSviewer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/cluster_dashboard.html">
 <span class="dropdown-text">클러스터 대시보드 (Shiny)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-appendix" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">부록 / Appendix</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-appendix">    
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/appendix_detailed_reporting.html">
 <span class="dropdown-text">상세 리포팅 방법론</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/appendix_core_reports.html">
 <span class="dropdown-text">상세 리포팅 — 핵심 역량</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/appendix_expand_reports.html">
 <span class="dropdown-text">상세 리포팅 — 확장 가능</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/appendix_gap_reports.html">
 <span class="dropdown-text">상세 리포팅 — 역량 공백</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/appendix_methodology.html">
 <span class="dropdown-text">클러스터링·키워드 방법론</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://kisti-globalrnd.github.io/kriss-databook-2025/docs/appendix.html">
 <span class="dropdown-text">용어 및 참고 / Glossary</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
    <a href="https://github.com/KISTI-GlobalRnD/kriss-databook-2025" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../docs/appendix_detailed_reporting.html">Appendices</a></li><li class="breadcrumb-item"><a href="../../../docs/appendix_gap_reports.html">상세 리포트 — 역량 공백</a></li><li class="breadcrumb-item"><a href="../../../docs/detailed_reports/cluster_169/report.html"><span class="chapter-number">_</span>&nbsp; <span class="chapter-title">30-169 - 위상 양자물질 전자구조 측정 (역량 공백)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
        <div class="sidebar-tools-collapse">
    <a href="https://kisti-globalrnd.github.io/kriss-databook-2025/" title="웹 버전 보기" class="quarto-navigation-tool px-1" aria-label="웹 버전 보기"><i class="bi bi-browser"></i></a>
</div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">서문 / Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../book_part1_landscape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">문헌 집합 및 연구지형도 구축</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../book_part2_capability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">기관 연구역량 진단</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../book_part3_emerging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">유망 연구영역 도출</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/appendix_detailed_reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">상세 리포팅 방법론</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">상세 리포트 — 핵심 역량</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/appendix_core_reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">상세 리포팅 — 핵심 역량</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_12/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">9-12 - 배터리 양극·계면 측정 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_173/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">10-173 - 2차원·산화물 가스센서 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_24/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">11-24 - 폴리머 난연성 측정 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_167/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">12-167 - 스핀전류 변환·제어 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_182/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">20-182 - 다이아몬드결함양자센서 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_69/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">34-69 - 메타표면 광학소자 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_77/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">36-77 - 2차원 광전소자 측정 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_145/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">37-145 - 광음향·초음파 나노진단치료 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_127/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">41-127 - 뇌파 감정상태 측정 (핵심 역량)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_178/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">43-178 - 현장진단 바이오센서 (핵심 역량)</span></span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">상세 리포트 — 확장 가능</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/appendix_expand_reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">M</span>&nbsp; <span class="chapter-title">상세 리포팅 — 확장 가능</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_117/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">N</span>&nbsp; <span class="chapter-title">2-117 - 레이저 미량가스 분광측정 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_154/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">O</span>&nbsp; <span class="chapter-title">7-154 - 리튬이온전지 예지진단 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_191/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">P</span>&nbsp; <span class="chapter-title">9-191 - 물분해 전기촉매 측정 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_15/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">Q</span>&nbsp; <span class="chapter-title">11-15 - 전자파 차폐·흡수 복합재 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_123/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">R</span>&nbsp; <span class="chapter-title">25-123 - 위상광자·비에르미트상 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_176/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">S</span>&nbsp; <span class="chapter-title">25-176 - 양자다체 비평형 동역학 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_79/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">T</span>&nbsp; <span class="chapter-title">37-79 - 미세·나노입자 계측표준 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_84/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">U</span>&nbsp; <span class="chapter-title">38-84 - 양자알고리즘·오류정정 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_107/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">V</span>&nbsp; <span class="chapter-title">38-107 - 초전도 회로 양자전기역학 (확장 가능)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_141/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">W</span>&nbsp; <span class="chapter-title">41-141 - 신축성 전자피부 센서 (확장 가능)</span></span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">상세 리포트 — 역량 공백</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/appendix_gap_reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">X</span>&nbsp; <span class="chapter-title">상세 리포팅 — 역량 공백</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_189/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">Y</span>&nbsp; <span class="chapter-title">9-189 - 다공성골격 가스분리 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_159/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">Z</span>&nbsp; <span class="chapter-title">11-159 - 나노셀룰로오스 소재측정 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_112/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">[</span>&nbsp; <span class="chapter-title">15-112 - 업컨버전 나노입자 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_133/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">\</span>&nbsp; <span class="chapter-title">18-133 - 적층 바이오제조 측정 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_131/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">]</span>&nbsp; <span class="chapter-title">26-131 - 중력파 검출·분석 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_179/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">^</span>&nbsp; <span class="chapter-title">29-179 - 프로테오믹스 질량분석 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_169/report.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">_</span>&nbsp; <span class="chapter-title">30-169 - 위상 양자물질 전자구조 측정 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_62/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number"><code>&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;32-62 - 집적 광주파수콤 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-next"} [&lt;span class='chapter-number'&gt;^&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;29-179 - 프로테오믹스 질량분석 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-prev"} [&lt;span class='chapter-number'&gt;1&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;서문 / Preface&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/index.html&lt;span-class='chapter-number'&gt;1&lt;/span&gt;--&lt;span-class='chapter-title'&gt;서문-/-Preface&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;2&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;문헌 집합 및 연구지형도 구축&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/book_part1_landscape.html&lt;span-class='chapter-number'&gt;2&lt;/span&gt;--&lt;span-class='chapter-title'&gt;문헌-집합-및-연구지형도-구축&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;3&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;기관 연구역량 진단&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/book_part2_capability.html&lt;span-class='chapter-number'&gt;3&lt;/span&gt;--&lt;span-class='chapter-title'&gt;기관-연구역량-진단&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;4&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;유망 연구영역 도출&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/book_part3_emerging.html&lt;span-class='chapter-number'&gt;4&lt;/span&gt;--&lt;span-class='chapter-title'&gt;유망-연구영역-도출&lt;/span&gt;"} [Appendices]{.hidden render-id="quarto-int-sidebar:quarto-sidebar-section-1"} [&lt;span class='chapter-number'&gt;A&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;상세 리포팅 방법론&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/appendix_detailed_reporting.html&lt;span-class='chapter-number'&gt;A&lt;/span&gt;--&lt;span-class='chapter-title'&gt;상세-리포팅-방법론&lt;/span&gt;"} [상세 리포트 — 핵심 역량]{.hidden render-id="quarto-int-sidebar:quarto-sidebar-section-2"} [&lt;span class='chapter-number'&gt;B&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;상세 리포팅 — 핵심 역량&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/appendix_core_reports.html&lt;span-class='chapter-number'&gt;B&lt;/span&gt;--&lt;span-class='chapter-title'&gt;상세-리포팅-—-핵심-역량&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;C&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;9-12 - 배터리 양극·계면 측정 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_12/report.html&lt;span-class='chapter-number'&gt;C&lt;/span&gt;--&lt;span-class='chapter-title'&gt;9-12---배터리-양극·계면-측정-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;D&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;10-173 - 2차원·산화물 가스센서 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_173/report.html&lt;span-class='chapter-number'&gt;D&lt;/span&gt;--&lt;span-class='chapter-title'&gt;10-173---2차원·산화물-가스센서-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;E&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;11-24 - 폴리머 난연성 측정 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_24/report.html&lt;span-class='chapter-number'&gt;E&lt;/span&gt;--&lt;span-class='chapter-title'&gt;11-24---폴리머-난연성-측정-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;F&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;12-167 - 스핀전류 변환·제어 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_167/report.html&lt;span-class='chapter-number'&gt;F&lt;/span&gt;--&lt;span-class='chapter-title'&gt;12-167---스핀전류-변환·제어-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;G&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;20-182 - 다이아몬드결함양자센서 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_182/report.html&lt;span-class='chapter-number'&gt;G&lt;/span&gt;--&lt;span-class='chapter-title'&gt;20-182---다이아몬드결함양자센서-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;H&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;34-69 - 메타표면 광학소자 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_69/report.html&lt;span-class='chapter-number'&gt;H&lt;/span&gt;--&lt;span-class='chapter-title'&gt;34-69---메타표면-광학소자-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;I&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;36-77 - 2차원 광전소자 측정 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_77/report.html&lt;span-class='chapter-number'&gt;I&lt;/span&gt;--&lt;span-class='chapter-title'&gt;36-77---2차원-광전소자-측정-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;J&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;37-145 - 광음향·초음파 나노진단치료 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_145/report.html&lt;span-class='chapter-number'&gt;J&lt;/span&gt;--&lt;span-class='chapter-title'&gt;37-145---광음향·초음파-나노진단치료-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;K&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;41-127 - 뇌파 감정상태 측정 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_127/report.html&lt;span-class='chapter-number'&gt;K&lt;/span&gt;--&lt;span-class='chapter-title'&gt;41-127---뇌파-감정상태-측정-(핵심-역량)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;L&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;43-178 - 현장진단 바이오센서 (핵심 역량)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_178/report.html&lt;span-class='chapter-number'&gt;L&lt;/span&gt;--&lt;span-class='chapter-title'&gt;43-178---현장진단-바이오센서-(핵심-역량)&lt;/span&gt;"} [상세 리포트 — 확장 가능]{.hidden render-id="quarto-int-sidebar:quarto-sidebar-section-3"} [&lt;span class='chapter-number'&gt;M&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;상세 리포팅 — 확장 가능&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/appendix_expand_reports.html&lt;span-class='chapter-number'&gt;M&lt;/span&gt;--&lt;span-class='chapter-title'&gt;상세-리포팅-—-확장-가능&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;N&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;2-117 - 레이저 미량가스 분광측정 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_117/report.html&lt;span-class='chapter-number'&gt;N&lt;/span&gt;--&lt;span-class='chapter-title'&gt;2-117---레이저-미량가스-분광측정-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;O&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;7-154 - 리튬이온전지 예지진단 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_154/report.html&lt;span-class='chapter-number'&gt;O&lt;/span&gt;--&lt;span-class='chapter-title'&gt;7-154---리튬이온전지-예지진단-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;P&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;9-191 - 물분해 전기촉매 측정 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_191/report.html&lt;span-class='chapter-number'&gt;P&lt;/span&gt;--&lt;span-class='chapter-title'&gt;9-191---물분해-전기촉매-측정-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;Q&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;11-15 - 전자파 차폐·흡수 복합재 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_15/report.html&lt;span-class='chapter-number'&gt;Q&lt;/span&gt;--&lt;span-class='chapter-title'&gt;11-15---전자파-차폐·흡수-복합재-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;R&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;25-123 - 위상광자·비에르미트상 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_123/report.html&lt;span-class='chapter-number'&gt;R&lt;/span&gt;--&lt;span-class='chapter-title'&gt;25-123---위상광자·비에르미트상-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;S&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;25-176 - 양자다체 비평형 동역학 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_176/report.html&lt;span-class='chapter-number'&gt;S&lt;/span&gt;--&lt;span-class='chapter-title'&gt;25-176---양자다체-비평형-동역학-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;T&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;37-79 - 미세·나노입자 계측표준 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_79/report.html&lt;span-class='chapter-number'&gt;T&lt;/span&gt;--&lt;span-class='chapter-title'&gt;37-79---미세·나노입자-계측표준-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;U&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;38-84 - 양자알고리즘·오류정정 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_84/report.html&lt;span-class='chapter-number'&gt;U&lt;/span&gt;--&lt;span-class='chapter-title'&gt;38-84---양자알고리즘·오류정정-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;V&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;38-107 - 초전도 회로 양자전기역학 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_107/report.html&lt;span-class='chapter-number'&gt;V&lt;/span&gt;--&lt;span-class='chapter-title'&gt;38-107---초전도-회로-양자전기역학-(확장-가능)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;W&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;41-141 - 신축성 전자피부 센서 (확장 가능)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_141/report.html&lt;span-class='chapter-number'&gt;W&lt;/span&gt;--&lt;span-class='chapter-title'&gt;41-141---신축성-전자피부-센서-(확장-가능)&lt;/span&gt;"} [상세 리포트 — 역량 공백]{.hidden render-id="quarto-int-sidebar:quarto-sidebar-section-4"} [&lt;span class='chapter-number'&gt;X&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;상세 리포팅 — 역량 공백&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/appendix_gap_reports.html&lt;span-class='chapter-number'&gt;X&lt;/span&gt;--&lt;span-class='chapter-title'&gt;상세-리포팅-—-역량-공백&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;Y&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;9-189 - 다공성골격 가스분리 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_189/report.html&lt;span-class='chapter-number'&gt;Y&lt;/span&gt;--&lt;span-class='chapter-title'&gt;9-189---다공성골격-가스분리-(역량-공백)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;Z&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;11-159 - 나노셀룰로오스 소재측정 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_159/report.html&lt;span-class='chapter-number'&gt;Z&lt;/span&gt;--&lt;span-class='chapter-title'&gt;11-159---나노셀룰로오스-소재측정-(역량-공백)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;[&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;15-112 - 업컨버전 나노입자 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_112/report.html&lt;span-class='chapter-number'&gt;[&lt;/span&gt;--&lt;span-class='chapter-title'&gt;15-112---업컨버전-나노입자-(역량-공백)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;\&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;18-133 - 적층 바이오제조 측정 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_133/report.html&lt;span-class='chapter-number'&gt;\&lt;/span&gt;--&lt;span-class='chapter-title'&gt;18-133---적층-바이오제조-측정-(역량-공백)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;]&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;26-131 - 중력파 검출·분석 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_131/report.html&lt;span-class='chapter-number'&gt;]&lt;/span&gt;--&lt;span-class='chapter-title'&gt;26-131---중력파-검출·분석-(역량-공백)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;^&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;29-179 - 프로테오믹스 질량분석 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_179/report.html&lt;span-class='chapter-number'&gt;^&lt;/span&gt;--&lt;span-class='chapter-title'&gt;29-179---프로테오믹스-질량분석-(역량-공백)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;_&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;30-169 - 위상 양자물질 전자구조 측정 (역량 공백)&lt;/span&gt;]{.hidden render-id="quarto-int-sidebar:/docs/detailed_reports/cluster_169/report.html&lt;span-class='chapter-number'&gt;_&lt;/span&gt;--&lt;span-class='chapter-title'&gt;30-169---위상-양자물질-전자구조-측정-(역량-공백)&lt;/span&gt;"} [&lt;span class='chapter-number'&gt;</code></span>&nbsp; <span class="chapter-title">32-62 - 집적 광주파수콤 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_162/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">a</span>&nbsp; <span class="chapter-title">34-162 - 궤도각운동량 광계측 (역량 공백)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/detailed_reports/cluster_125/report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">b</span>&nbsp; <span class="chapter-title">43-125 - 유전체 변이 측정표준 (역량 공백)</span></span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/appendix_methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">c</span>&nbsp; <span class="chapter-title">클러스터링·키워드 방법론</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">d</span>&nbsp; <span class="chapter-title">용어 및 참고 / Glossary</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#개요" id="toc-개요" class="nav-link active" data-scroll-target="#개요">1. 개요</a>
  <ul class="collapse">
  <li><a href="#클러스터-설명" id="toc-클러스터-설명" class="nav-link" data-scroll-target="#클러스터-설명">1-1. 클러스터 설명</a></li>
  <li><a href="#측정-과학-관점-해석" id="toc-측정-과학-관점-해석" class="nav-link" data-scroll-target="#측정-과학-관점-해석">1-2. 측정 과학 관점 해석</a></li>
  </ul></li>
  <li><a href="#클러스터-세부지표" id="toc-클러스터-세부지표" class="nav-link" data-scroll-target="#클러스터-세부지표">2. 클러스터 세부지표</a>
  <ul class="collapse">
  <li><a href="#전체-문헌-수-추이연도별" id="toc-전체-문헌-수-추이연도별" class="nav-link" data-scroll-target="#전체-문헌-수-추이연도별">2-1. 전체 문헌 수 추이(연도별)</a></li>
  <li><a href="#퍼센타일요약" id="toc-퍼센타일요약" class="nav-link" data-scroll-target="#퍼센타일요약">2-2. 퍼센타일(요약)</a></li>
  <li><a href="#kriss-기여" id="toc-kriss-기여" class="nav-link" data-scroll-target="#kriss-기여">2-3. KRISS 기여</a></li>
  <li><a href="#간단-해석" id="toc-간단-해석" class="nav-link" data-scroll-target="#간단-해석">2-4. 간단 해석</a></li>
  </ul></li>
  <li><a href="#지식기반-인접-클러스터키워드" id="toc-지식기반-인접-클러스터키워드" class="nav-link" data-scroll-target="#지식기반-인접-클러스터키워드">3. 지식기반 인접 클러스터·키워드</a>
  <ul class="collapse">
  <li><a href="#지식기반-인접-클러스터eaaa" id="toc-지식기반-인접-클러스터eaaa" class="nav-link" data-scroll-target="#지식기반-인접-클러스터eaaa">3-1. 지식기반 인접 클러스터(EA/AA)</a></li>
  <li><a href="#워드클라우드" id="toc-워드클라우드" class="nav-link" data-scroll-target="#워드클라우드">3-2. 워드클라우드</a></li>
  <li><a href="#키워드-시계열비율-20152024" id="toc-키워드-시계열비율-20152024" class="nav-link" data-scroll-target="#키워드-시계열비율-20152024">3-3. 키워드 시계열(비율, 2015–2024)</a></li>
  <li><a href="#주요-키워드기간별-비율문서수" id="toc-주요-키워드기간별-비율문서수" class="nav-link" data-scroll-target="#주요-키워드기간별-비율문서수">3-4. 주요 키워드(기간별 비율·문서수)</a></li>
  </ul></li>
  <li><a href="#기관-분석20202024" id="toc-기관-분석20202024" class="nav-link" data-scroll-target="#기관-분석20202024">4. 기관 분석(2020–2024)</a>
  <ul class="collapse">
  <li><a href="#개-기관-성과-지표" id="toc-개-기관-성과-지표" class="nav-link" data-scroll-target="#개-기관-성과-지표">4-1. 10개 기관 성과 지표</a></li>
  <li><a href="#상위-기관문헌-수-기준-20202024" id="toc-상위-기관문헌-수-기준-20202024" class="nav-link" data-scroll-target="#상위-기관문헌-수-기준-20202024">4-2. 상위 기관(문헌 수 기준, 2020–2024)</a></li>
  <li><a href="#기관별-초록-기반-요약20202024" id="toc-기관별-초록-기반-요약20202024" class="nav-link" data-scroll-target="#기관별-초록-기반-요약20202024">4-3. 기관별 초록 기반 요약(2020–2024)</a></li>
  </ul></li>
  <li><a href="#정책부합성분포" id="toc-정책부합성분포" class="nav-link" data-scroll-target="#정책부합성분포">5. 정책부합성(분포)</a>
  <ul class="collapse">
  <li><a href="#분포비율건수" id="toc-분포비율건수" class="nav-link" data-scroll-target="#분포비율건수">5-1. 분포(비율%/건수)</a></li>
  <li><a href="#정책부합성-해석" id="toc-정책부합성-해석" class="nav-link" data-scroll-target="#정책부합성-해석">5-2. 정책부합성 해석</a></li>
  <li><a href="#분류-근거-예시" id="toc-분류-근거-예시" class="nav-link" data-scroll-target="#분류-근거-예시">5-3. 분류 근거 예시</a></li>
  </ul></li>
  <li><a href="#요약" id="toc-요약" class="nav-link" data-scroll-target="#요약">6. 요약</a></li>
  <li><a href="#부록.-데이터-커버리지주의" id="toc-부록.-데이터-커버리지주의" class="nav-link" data-scroll-target="#부록.-데이터-커버리지주의">부록. 데이터 커버리지·주의</a></li>
  <li><a href="#부록.-약어" id="toc-부록.-약어" class="nav-link" data-scroll-target="#부록.-약어">부록. 약어</a></li>
  <li><a href="#부록.-상위-인용-논문" id="toc-부록.-상위-인용-논문" class="nav-link" data-scroll-target="#부록.-상위-인용-논문">부록. 상위 인용 논문</a>
  <ul class="collapse">
  <li><a href="#부록-1.-전체기간-인용수-상위-5개" id="toc-부록-1.-전체기간-인용수-상위-5개" class="nav-link" data-scroll-target="#부록-1.-전체기간-인용수-상위-5개">부록-1. 전체기간 인용수 상위 5개</a></li>
  <li><a href="#부록-2.-최근-5년20202024-인용수-상위-5개" id="toc-부록-2.-최근-5년20202024-인용수-상위-5개" class="nav-link" data-scroll-target="#부록-2.-최근-5년20202024-인용수-상위-5개">부록-2. 최근 5년(2020–2024) 인용수 상위 5개</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/KISTI-GlobalRnD/kriss-databook-2025/blob/main/docs/detailed_reports/cluster_169/report.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/KISTI-GlobalRnD/kriss-databook-2025/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../docs/appendix_detailed_reporting.html">Appendices</a></li><li class="breadcrumb-item"><a href="../../../docs/appendix_gap_reports.html">상세 리포트 — 역량 공백</a></li><li class="breadcrumb-item"><a href="../../../docs/detailed_reports/cluster_169/report.html"><span class="chapter-number">_</span>&nbsp; <span class="chapter-title">30-169 - 위상 양자물질 전자구조 측정 (역량 공백)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Appendix _ — 30-169 - 위상 양자물질 전자구조 측정 (역량 공백)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<style>
@page {
  size: A4;
  margin: 30mm 18mm 30mm 18mm;
}
</style>
<section id="개요" class="level2">
<h2 class="anchored" data-anchor-id="개요">1. 개요</h2>
<blockquote class="blockquote">
<p>유형: 역량 공백 — 내부 지표 기준에서 상대적으로 부족 축이 표시된 유형.</p>
<p>연관 그룹: 첨단소재측정그룹, 양자전기자기측정그룹, 소재물성측정그룹</p>
</blockquote>
<section id="클러스터-설명" class="level3">
<h3 class="anchored" data-anchor-id="클러스터-설명">1-1. 클러스터 설명</h3>
<p>이 클러스터의 핵심은 <strong>topological insulator</strong>와 <strong>weyl semimetal</strong> 같은 위상 양자물질에서 전자 밴드의 “위상(위상수, 위상 불변량)”이 실제로 어떤 전기·자기 응답으로 드러나는지를 측정으로 연결해 내는 것입니다. 기존의 일반적인 전기전도/저항 측정만으로는 벌크(재료 내부) 전도와 표면 전도가 섞이거나, 결함·도핑·두께 같은 공정 변수가 신호를 바꿔서 “위상에서 온 효과”와 “일반적인 재료 효과”를 구분하기가 어렵습니다. 여기서 위상 양자물질은 전자 밴드가 단순히 “에너지-운동량 관계”만 가지는 것이 아니라, 전자 파동함수의 기하학적 성질(예: 베리 위상) 이 물질의 수송·광응답에 직접 관여하도록 구조화된 물질을 뜻합니다.</p>
<p>이 기술은 보통 저온과 강한 자기장 같은 조건에서 시작합니다. 입력으로는 시료에 전류를 흘리거나 전압을 걸고, 필요하면 게이트 전압으로 캐리어 밀도(페르미 준위 위치) 를 조절하며, 자기장을 걸어 전자 궤도 운동을 양자화하거나 자성 질서를 정렬시킵니다. 센서 반응은 홀저항, 종저항, 자화, 열전 신호(네른스트 등) 처럼 전기·자기·열전 응답이 바뀌는 형태로 나타나며, 때로는 각도분해 광전자분광으로 표면의 디랙 원뿔이나 페르미 아크 같은 전자구조를 직접 따라갑니다. 출력은 결국 “특정 응답이 어떤 전자구조(표면 상태/벌크 상태) 와 어떤 위상 성질(예: 베리 곡률) 에 의해 지배되는지”를 정량적으로 설명할 수 있는 파라미터(예: 이동도, 유효질량, 양자진동 주기, 홀 전도도) 로 정리됩니다.</p>
<p>이때 <strong>anomalous hall effect</strong>는 특히 중요한 관문입니다. 이는 외부 자기장이 없어도(또는 작은 자기장에서도) 자성 질서와 스핀-궤도 결합이 결합된 전자구조 때문에 횡방향 전압이 생기는 현상으로, 전자 밴드 안의 베리 곡률이 커질수록 강한 신호로 나타납니다. 반대로 <strong>surface</strong>는 위상 물질의 핵심 “경계 상태”가 존재하는 공간이어서, 표면에서만 흐르는 전류가 벌크 전류와 섞이지 않게 만들거나(혹은 섞임을 분해해 내거나) 표면 전자구조의 에너지 갭, 디랙 원뿔 형태 등을 구분하는 것이 측정의 성패를 좌우합니다. 최근에는 <strong>kagome</strong> 격자 기반 금속처럼 구조 자체가 전자 밴드에 특이점을 만들어 베리 곡률과 수송 응답을 크게 만들 수 있는 계열도 함께 다룹니다.</p>
</section>
<section id="측정-과학-관점-해석" class="level3">
<h3 class="anchored" data-anchor-id="측정-과학-관점-해석">1-2. 측정 과학 관점 해석</h3>
<p>이 주제의 측정 원리는 “전자 밴드 위상 → 측정 가능한 응답”의 변환을 정밀하게 구현하는 것입니다. 먼저 측정 대상은 위상 양자물질에서의 전기저항·홀저항·자화·열전 계수·광응답처럼 실험적으로 읽을 수 있는 물리량이며, 그 물리량이 밴드 위상(예: 베리 위상) 이나 표면 상태의 존재 여부에 의해 좌우된다는 점을 이용합니다. 다음으로 센서 반응은 자기장 인가나 게이팅에 의해 페르미 준위가 이동하거나, 자성 질서가 정렬되거나, 양자진동이 나타나는 등 전자 수송의 “상태”가 달라지면서 저항 텐서(종·횡 성분) 나 열전 신호가 함께 바뀌는 형태로 나타납니다. 마지막으로 신호 판독은 전압·전류 측정으로 저항과 홀 성분을 분리하고, 필요하면 자화·온도 구배를 함께 제어해 열전 성분을 읽거나, 각도분해 광전자분광으로 전자구조의 에너지-운동량 분산을 직접 재구성하는 방식으로 이루어집니다.</p>
<p>성능지표는 “위상에서 온 미묘한 신호를 얼마나 분명하게 떼어낼 수 있는가”를 중심으로 잡습니다. 예를 들어 <strong>anomalous hall effect</strong>는 재료의 자화뿐 아니라 밴드의 베리 곡률에 민감하므로, 홀 전도도(또는 홀 각) 처럼 신호 크기를 안정적으로 비교할 수 있는 지표가 중요해집니다. <strong>surface</strong> 기여를 분해하려면 벌크 전도 채널이 얼마나 억제되는지, 혹은 두 채널을 모델로 동시에 적합할 만큼 데이터 품질이 충분한지가 핵심입니다. 또한 <strong>field</strong>(자기장) 는 양자진동과 같은 주파수 성분을 만들어 유효질량·캐리어 밀도 등 전자구조 파라미터를 꺼내는 역할을 하므로, 자장 세기와 방향 제어의 정밀도가 곧 “전자구조를 얼마나 선명하게 지도화할 수 있는지”로 연결됩니다.</p>
<p>재현성과 비교 가능성은 시료·환경·프로토콜에 매우 민감합니다. 같은 <strong>topological insulator</strong>라도 결함이 많아 벌크가 잘 도전성이 되면 표면 수송이 가려지고, 표면이 산화되거나 표면 전하가 변하면 밴드 휨이 생겨 표면 근처에 추가적인 전도 채널이 형성될 수 있습니다. 박막에서는 두께가 얇아질수록 위·아래 표면 상태가 서로 결합해 에너지 갭이 생길 수 있고, 게이팅 효율도 두께와 기판 조건에 의해 달라집니다. <strong>weyl semimetal</strong>이나 <strong>kagome</strong> 계열처럼 베리 곡률이 큰 물질은 자성 상태(예: 강자성/반강자성, 도메인 상태) 와 온도 조건에 따라 홀·네른스트 신호의 형태가 달라질 수 있어, 자화 이력(히스테리시스) 과 측정 순서가 결과에 직접 영향을 줍니다.</p>
<p>따라서 측정 과학 관점에서는 “저온·고자장 환경에서의 전기·자기·열전·광학 측정 교정, 불확도 평가, 표준 시편, 측정 프로토콜”이 함께 정리되어야 합니다. 동일한 장치로 측정하더라도 온도 안정도, 자기장 정렬 오차, 접촉저항과 배선 열기전력, 시료의 두께·조성·계면 품질 같은 조건이 달라지면 홀 저항과 종저항의 분해가 달라지고, 결과적으로 위상에서 기인한 신호의 크기와 해석이 달라질 수 있기 때문입니다.</p>
</section>
</section>
<section id="클러스터-세부지표" class="level2">
<h2 class="anchored" data-anchor-id="클러스터-세부지표">2. 클러스터 세부지표</h2>
<section id="전체-문헌-수-추이연도별" class="level3">
<h3 class="anchored" data-anchor-id="전체-문헌-수-추이연도별">2-1. 전체 문헌 수 추이(연도별)</h3>
<p><a href="figures/02_docs_by_year.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="figures/02_docs_by_year.svg" class="img-fluid"></a></p>
<blockquote class="blockquote">
<p>좌측 축은 해당 클러스터, 우측 축은 195개 micro 전체 합계의 연도별 문헌 수(N_docs) 입니다(절대값 비교가 아니라 추세 비교 목적).</p>
</blockquote>
<p>2000–2024 전체 기간의 연도별 문헌 수(UID 기준) 추이를 표시했습니다. 최근 5개년(2020–2024) 합계는 <strong>1,665편</strong>이며, 같은 기간 micro 전체 합계는 <strong>450,518편</strong>입니다. 참고로 2000–2024 기간 micro 전체 누적 합계는 <strong>1,099,738편</strong>이며, 2024년 micro 연도별 합계는 <strong>113,736편</strong>입니다.</p>
</section>
<section id="퍼센타일요약" class="level3">
<h3 class="anchored" data-anchor-id="퍼센타일요약">2-2. 퍼센타일(요약)</h3>
<p>아래 지표는 입력 데이터의 퍼센타일(0~100) 기준이며, 숫자가 클수록 상대적 위치가 높습니다. ‘스코프 다양성(폭)’은 유망성 판단이 아니라 주제 범위/세분화 정도를 나타내는 보조 지표로 해석합니다.</p>
<table class="table">
<thead>
<tr class="header">
<th>지표</th>
<th style="text-align: right;">퍼센타일</th>
<th>수준</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>성장성</td>
<td style="text-align: right;">81.03</td>
<td>상위 30% (우수)</td>
</tr>
<tr class="even">
<td>파급력</td>
<td style="text-align: right;">94.87</td>
<td>상위 10% (매우 우수)</td>
</tr>
<tr class="odd">
<td>기술진보기여도</td>
<td style="text-align: right;">22.56</td>
<td>하위 60% (보통 이하)</td>
</tr>
<tr class="even">
<td>스코프 다양성(폭)</td>
<td style="text-align: right;">12.31</td>
<td>하위 60% (보통 이하)</td>
</tr>
<tr class="odd">
<td>종합(총점)</td>
<td style="text-align: right;">80.51</td>
<td>상위 30% (우수)</td>
</tr>
</tbody>
</table>
</section>
<section id="kriss-기여" class="level3">
<h3 class="anchored" data-anchor-id="kriss-기여">2-3. KRISS 기여</h3>
<p>RTA·논문수(N_docs) 는 양적 활동도, Excellence10은 상위 10% 인용 논문 비중(%) 으로 질적 성과를 나타냅니다. 단, Excellence10은 표본 수(N_docs) 가 적을 때 변동성이 커 참고용으로 해석하는 것이 안전합니다.</p>
<table class="table">
<thead>
<tr class="header">
<th>항목</th>
<th style="text-align: right;">값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>KRISS RTA(최근 5개년)</td>
<td style="text-align: right;">1.52</td>
</tr>
<tr class="even">
<td>KRISS Excellence10(최근 5개년, %)</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td>KRISS 논문수(최근 5개년)</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</section>
<section id="간단-해석" class="level3">
<h3 class="anchored" data-anchor-id="간단-해석">2-4. 간단 해석</h3>
<p>파급력 퍼센타일이 상위 10% 수준으로 집계됩니다.</p>
</section>
</section>
<section id="지식기반-인접-클러스터키워드" class="level2">
<h2 class="anchored" data-anchor-id="지식기반-인접-클러스터키워드">3. 지식기반 인접 클러스터·키워드</h2>
<section id="지식기반-인접-클러스터eaaa" class="level3">
<h3 class="anchored" data-anchor-id="지식기반-인접-클러스터eaaa">3-1. 지식기반 인접 클러스터(EA/AA)</h3>
<p>용어: ego는 현재 클러스터, alter는 유사도 기준으로 연결된 이웃 클러스터를 뜻합니다. 표의 <code>구분</code>은 EA(ego–alter) / AA(alter–alter) 로 표기합니다.</p>
<p>역량 공백 유형 클러스터로, RTA ≥ 1 기관은 NIST, NMIJ/AIST로 제시됩니다. KRISS 최근 5개년 기준에서 핵심 역량 기준 3조건 중 부족한 축은 RTA·N_docs·Excellence10입니다.</p>
<p><a href="figures/01_ego_network.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="figures/01_ego_network.png" class="img-fluid"></a></p>
<table class="table table-sm" style="table-layout: fixed; width: 100%;">
<colgroup>
<col style="width: 8%;">
<col style="width: 34%;">
<col style="width: 10%;">
<col style="width: 8%;">
<col style="width: 40%;">
</colgroup>
<thead>
<tr>
<th style="text-align: left; vertical-align: top; white-space: nowrap;">
구분
</th>
<th style="text-align: left; vertical-align: top;">
클러스터
</th>
<th style="text-align: left; vertical-align: top; white-space: nowrap;">
유형
</th>
<th style="text-align: right; vertical-align: top; white-space: nowrap;">
유사도
</th>
<th style="text-align: left; vertical-align: top;">
대표 키워드
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
EA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
39-85 - 철계 초전도체 물성
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
unknown
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
1.00
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
superconductor, superconducting, iron, superconductivity, doping
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
EA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
39-132 - MgB2 초전도 특성
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
unknown
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.99
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
mgb2, superconductor, superconducting, critical current, doping
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
EA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
39-150 - REBCO 나노핀닝
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
unknown
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.99
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
high temperature superconductor, bi sr, superconductor, copper, maglev
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
EA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
14-126 - 키타예프 스핀액체 계측
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
unknown
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.94
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
temperature, field, phase, interaction, antiferromagnetic
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
EA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
25-123 - 위상광자·비에르미트상
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.61
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
spin orbit coupling, boson, topological, photonics, fermions
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
EA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
20-76 - 광펌핑 자력계
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.51
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
hertz, field, squid, magnetometer, measurement
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
EA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
38-107 - 초전도 회로 양자전기역학
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.46
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
superconductor, qubit, state, coupling, superconducting
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
25-176 - 양자다체 비평형 동역학
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.90
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
many-body localization, quantum many-body, many-body systems, out-of-time, matrix product state
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
25-83 - 광격자 초저온 원자
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.88
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
bose-hubbard model, one-dimensional, boson, fermion, hubbard model
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
20-124 - 광자 양자정보기술
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
핵심 역량
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.85
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
photon, entanglement, states, detector, qubit
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
38-84 - 양자알고리즘·오류정정
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.83
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
quantum computer, quantum algorithm, qubit, gate, states
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
25-109 - 페시바흐 페르미 초유체
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.82
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
bcs-bec crossover, three-body, fermions, feshbach resonance, atom
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
25-48 - 보스응축체 비선형 여기
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.79
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
bose-einstein condensate, soliton, state, solitons in, superfluid
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
20-103 - 양자광 메모리
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.79
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
atom, electromagnetically induced transparency, photon, atomic, light
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
25-43 - 초저온 극성분자
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.79
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
polar molecule, dipolar bose-einstein condensate, ultracold molecule, molecule, state
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
40-119 - 원자·이온 양자측정
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.78
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
rydberg atom, atom, state, ion, rydberg
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
20-71 - 양자 비국소성 검증
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.78
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
inequality, device-independent, einstein-podolsky, bell inequality, entanglement
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
20-156 - 광기계 양자측정
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.72
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
optomechanical, resonator, mode, gyroscope, coupling
</td>
</tr>
<tr>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
AA
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
20-32 - 양자점 단일광자원
</td>
<td style="text-align: left; vertical-align: top; white-space: nowrap;">
확장 가능
</td>
<td style="text-align: right; vertical-align: top; white-space: nowrap;">
0.56
</td>
<td style="text-align: left; vertical-align: top; word-break: break-word; hyphens: auto;">
quantum dots, inas, photon, emission, state
</td>
</tr>
</tbody>
</table>
</section>
<section id="워드클라우드" class="level3">
<h3 class="anchored" data-anchor-id="워드클라우드">3-2. 워드클라우드</h3>
<p><a href="figures/03_wordcloud.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="figures/03_wordcloud.png" class="img-fluid"></a></p>
<p>생성 방식: 클러스터 전체 초록에서 stopword를 제거하고, 단어·bi-gram 빈도를 계산했습니다(상위 3200개). 여기에 입력 키워드 빈도 정보를 <code>alpha=0.5</code>로 가중 결합해(스케일 정규화 후) 표현했습니다.</p>
</section>
<section id="키워드-시계열비율-20152024" class="level3">
<h3 class="anchored" data-anchor-id="키워드-시계열비율-20152024">3-3. 키워드 시계열(비율, 2015–2024)</h3>
<p><a href="figures/03_keywords_trend.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="figures/03_keywords_trend.svg" class="img-fluid"></a></p>
<p><code>비율(%) = (해당 연도·클러스터에서 키워드가 포함된 문서 수 / 같은 연도·클러스터 전체 문서 수) × 100</code> 위 heatmap은 상위 키워드의 비율(%) 을 <strong>키워드별 0~1 정규화(최대값=1)</strong>해 상대 변화를 보여줍니다.</p>
</section>
<section id="주요-키워드기간별-비율문서수" class="level3">
<h3 class="anchored" data-anchor-id="주요-키워드기간별-비율문서수">3-4. 주요 키워드(기간별 비율·문서수)</h3>
<p>기간은 2015–2024를 기준으로 하며, 초기(2015–2017), 중기(2018–2021), 후기(2022–2024) 로 3구간 요약합니다.</p>
<p>표의 각 셀은 <code>비율% (문서수)</code> 형식이며, 괄호 안 숫자는 해당 기간에 키워드가 포함된 문서 수(중복 제거) 입니다(동일 문서 내 다중 등장은 1회로 계산).</p>
<p>score는 클러스터 내 용어의 대표성을 나타내는 점수로, c‑TF‑IDF와 LLR을 z‑score 후 가중합해 계산합니다. 자세한 산출 방식은 분야별 상세 리포팅(본 보고서) 을 참고해 주십시오.</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>term</th>
<th style="text-align: right;">score</th>
<th style="text-align: right;">10년 합계(2015–2024)</th>
<th style="text-align: right;">초기(2015–2017)</th>
<th style="text-align: right;">중기(2018–2021)</th>
<th style="text-align: right;">후기(2022–2024)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>weyl semimetal</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">18.25% (504)</td>
<td style="text-align: right;">16.54% (109)</td>
<td style="text-align: right;">21.41% (219)</td>
<td style="text-align: right;">16.30% (176)</td>
</tr>
<tr class="even">
<td>topological insulator</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">46.81% (1,293)</td>
<td style="text-align: right;">56.60% (373)</td>
<td style="text-align: right;">51.03% (522)</td>
<td style="text-align: right;">36.85% (398)</td>
</tr>
<tr class="odd">
<td>superconductor</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">12.49% (345)</td>
<td style="text-align: right;">9.10% (60)</td>
<td style="text-align: right;">10.46% (107)</td>
<td style="text-align: right;">16.48% (178)</td>
</tr>
<tr class="even">
<td>fermions</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">8.98% (248)</td>
<td style="text-align: right;">12.14% (80)</td>
<td style="text-align: right;">9.38% (96)</td>
<td style="text-align: right;">6.67% (72)</td>
</tr>
<tr class="odd">
<td>bi2se3</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">17.78% (491)</td>
<td style="text-align: right;">28.22% (186)</td>
<td style="text-align: right;">18.18% (186)</td>
<td style="text-align: right;">11.02% (119)</td>
</tr>
<tr class="even">
<td>anomalous hall effect</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">19.23% (531)</td>
<td style="text-align: right;">9.56% (63)</td>
<td style="text-align: right;">21.70% (222)</td>
<td style="text-align: right;">22.78% (246)</td>
</tr>
<tr class="odd">
<td>surface</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">42.25% (1,167)</td>
<td style="text-align: right;">53.41% (352)</td>
<td style="text-align: right;">42.62% (436)</td>
<td style="text-align: right;">35.09% (379)</td>
</tr>
<tr class="even">
<td>field</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">34.21% (945)</td>
<td style="text-align: right;">31.11% (205)</td>
<td style="text-align: right;">36.46% (373)</td>
<td style="text-align: right;">33.98% (367)</td>
</tr>
<tr class="odd">
<td>mnbi2te4</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">9.34% (258)</td>
<td style="text-align: right;">0.00% (0)</td>
<td style="text-align: right;">11.44% (117)</td>
<td style="text-align: right;">13.06% (141)</td>
</tr>
<tr class="even">
<td>kagome</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">10.75% (297)</td>
<td style="text-align: right;">0.46% (3)</td>
<td style="text-align: right;">5.08% (52)</td>
<td style="text-align: right;">22.41% (242)</td>
</tr>
<tr class="odd">
<td>transition</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">25.96% (717)</td>
<td style="text-align: right;">20.49% (135)</td>
<td style="text-align: right;">25.71% (263)</td>
<td style="text-align: right;">29.54% (319)</td>
</tr>
<tr class="even">
<td>dirac</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">21.87% (604)</td>
<td style="text-align: right;">28.38% (187)</td>
<td style="text-align: right;">22.87% (234)</td>
<td style="text-align: right;">16.94% (183)</td>
</tr>
<tr class="odd">
<td>bi2te3</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">9.96% (275)</td>
<td style="text-align: right;">10.17% (67)</td>
<td style="text-align: right;">11.63% (119)</td>
<td style="text-align: right;">8.24% (89)</td>
</tr>
<tr class="even">
<td>te</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">25.74% (711)</td>
<td style="text-align: right;">23.98% (158)</td>
<td style="text-align: right;">28.45% (291)</td>
<td style="text-align: right;">24.26% (262)</td>
</tr>
<tr class="odd">
<td>transport</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">32.59% (900)</td>
<td style="text-align: right;">33.69% (222)</td>
<td style="text-align: right;">32.75% (335)</td>
<td style="text-align: right;">31.76% (343)</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="기관-분석20202024" class="level2">
<h2 class="anchored" data-anchor-id="기관-분석20202024">4. 기관 분석(2020–2024)</h2>
<section id="개-기관-성과-지표" class="level3">
<h3 class="anchored" data-anchor-id="개-기관-성과-지표">4-1. 10개 기관 성과 지표</h3>
<p>최근 5개년(2020–2024) 기준으로 10개 기관의 논문 수(N_docs), RTA, Excellence10(상위 10% 인용 논문 비중×100) 을 정리했습니다. N_docs·RTA는 양적 활동도, Excellence10은 질적 성과를 나타내며, 표본 수(N_docs) 가 적을 때 Excellence10은 변동성이 커 참고용으로 해석하는 것이 안전합니다.</p>
<table class="table">
<thead>
<tr class="header">
<th>기관</th>
<th style="text-align: right;">N_docs</th>
<th style="text-align: right;">RTA</th>
<th style="text-align: right;">Excellence10(%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NPLI</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;"><strong>11.76</strong></td>
<td style="text-align: right;">5.88</td>
</tr>
<tr class="even">
<td>NIST</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;"><strong>2.35</strong></td>
<td style="text-align: right;"><strong>23.53</strong></td>
</tr>
<tr class="odd">
<td><strong>KRISS</strong></td>
<td style="text-align: right;">9</td>
<td style="text-align: right;"><strong>1.52</strong></td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td>NMIJ/AIST</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;"><strong>3.07</strong></td>
<td style="text-align: right;"><strong>25.00</strong></td>
</tr>
<tr class="odd">
<td>NIM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">0.00*</td>
</tr>
<tr class="even">
<td>NPL</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.00*</td>
</tr>
<tr class="odd">
<td>PTB</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.00*</td>
</tr>
<tr class="even">
<td>BAM</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>INRIM</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>NRC</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>* N_docs &lt; 5인 경우 Excellence10은 표본 수 영향이 커 참고용으로 해석하는 것이 안전합니다.</p>
<p>요약: KRISS의 최근 5개년 논문 수는 <strong>9편</strong>이며, 비교기관 중 최대치는 <strong>68편</strong>입니다. KRISS RTA는 <strong>1.52</strong>이며, 비교기관 중 최대치는 <strong>11.76</strong>입니다. KRISS Excellence10은 <strong>0.00%</strong>이며, 비교기관 중 최대치는 <strong>25.00%</strong>입니다.</p>
</section>
<section id="상위-기관문헌-수-기준-20202024" class="level3">
<h3 class="anchored" data-anchor-id="상위-기관문헌-수-기준-20202024">4-2. 상위 기관(문헌 수 기준, 2020–2024)</h3>
<p><strong>전체(Top500 + BIPM) Top5</strong></p>
<table class="table table-sm" style="table-layout: fixed; width: 100%;">
<colgroup>
<col style="width: 4em;">
<col>
<col style="width: 6em;">
</colgroup>
<thead>
<tr>
<th style="text-align: right; white-space: nowrap;">
순위
</th>
<th>
기관
</th>
<th style="text-align: right; white-space: nowrap;">
N_docs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: right; white-space: nowrap;">
1
</td>
<td>
Chinese Academy of Sciences
</td>
<td style="text-align: right; white-space: nowrap;">
317
</td>
</tr>
<tr>
<td style="text-align: right; white-space: nowrap;">
2
</td>
<td>
Institute of Physics, CAS
</td>
<td style="text-align: right; white-space: nowrap;">
120
</td>
</tr>
<tr>
<td style="text-align: right; white-space: nowrap;">
3
</td>
<td>
Oak Ridge National Laboratory
</td>
<td style="text-align: right; white-space: nowrap;">
96
</td>
</tr>
<tr>
<td style="text-align: right; white-space: nowrap;">
4
</td>
<td>
Nanjing University
</td>
<td style="text-align: right; white-space: nowrap;">
89
</td>
</tr>
<tr>
<td style="text-align: right; white-space: nowrap;">
5
</td>
<td>
University of Science &amp; Technology of China, CAS
</td>
<td style="text-align: right; white-space: nowrap;">
84
</td>
</tr>
</tbody>
</table>
<p><strong>BIPM 한정 Top5</strong></p>
<table class="table table-sm" style="table-layout: fixed; width: 100%;">
<colgroup>
<col style="width: 4em;">
<col>
<col style="width: 6em;">
</colgroup>
<thead>
<tr>
<th style="text-align: right; white-space: nowrap;">
순위
</th>
<th>
기관
</th>
<th style="text-align: right; white-space: nowrap;">
N_docs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: right; white-space: nowrap;">
1
</td>
<td>
CSIR National Physical Laboratory of India [NPLI]
</td>
<td style="text-align: right; white-space: nowrap;">
68
</td>
</tr>
<tr>
<td style="text-align: right; white-space: nowrap;">
2
</td>
<td>
National Institute of Standards and Technology [NIST]
</td>
<td style="text-align: right; white-space: nowrap;">
51
</td>
</tr>
<tr>
<td style="text-align: right; white-space: nowrap;">
3
</td>
<td>
Korea Research Institute of Standards and Science [KRISS]
</td>
<td style="text-align: right; white-space: nowrap;">
9
</td>
</tr>
<tr>
<td style="text-align: right; white-space: nowrap;">
4
</td>
<td>
National Metrology Institute of Japan, AIST [NMIJ/AIST]
</td>
<td style="text-align: right; white-space: nowrap;">
8
</td>
</tr>
<tr>
<td style="text-align: right; white-space: nowrap;">
5
</td>
<td>
National Institute of Metrology [NIM]
</td>
<td style="text-align: right; white-space: nowrap;">
3
</td>
</tr>
</tbody>
</table>
</section>
<section id="기관별-초록-기반-요약20202024" class="level3">
<h3 class="anchored" data-anchor-id="기관별-초록-기반-요약20202024">4-3. 기관별 초록 기반 요약(2020–2024)</h3>
<p>대상 기관 선정 기준: 최근 5개년(2020–2024) 기준으로 RTA(revealed technological advantage) &gt; 0.8 및 문헌 수 &gt; 5인 기관을 포함하고, KRISS는 항상 포함했습니다.</p>
<ul>
<li><p><strong>NPLI</strong>: 스퍼터링 박막과 단결정 성장을 바탕으로 Bi₂Se₃ 계 위상절연체의 저온 전자수송과 진동 특성 규명에 집중하고 있습니다 (RTA 11.76, 문헌 68건). RF 마그네트론 스퍼터링으로 두께 40, 80, 160 nm의 Bi₂Se₃ 박막을 제작하고, 2–100 K에서의 자기저항과 낮은 자기장 자기전도도 양자보정을 통해 약한 반국소화와 갭리스 표면 상태의 거동을 정밀하게 추적합니다. 또한 633 K 증착 조건에서 Bi₂Se₃ 박막의 전기전도 및 열전 특성을 확보해 실온 부근에서 제벡 계수 -153~-236 μV/K 범위를 제시합니다. Nb₀.₂₅Bi₂Se₃ 단결정에서는 2.5 K 이하 초전도 전이를 확인하고, 2 K에서 Hc1 약 50 Oe 및 Hc2 900 Oe를 제시합니다 (총 인용수: 49).</p></li>
<li><p><strong>NMIJ/AIST</strong>: 위상 양자물질의 전자구조를 분광·수송 측정으로 검증하고, 이를 정밀 저항 표준으로 연결하는 연구에 집중하고 있습니다 (RTA 3.07, 문헌 8건). Bi₄Br₄에 대해 각분해 광전자 분광법(ARPES; angle-resolved photoemission spectroscopy) 으로 3차원 재료에서의 고차 위상절연체 특성을 제시하며, 적층에 따른 위상 전이 개념을 실험 데이터로 뒷받침합니다. 또한 영구 디스크 자석이 제공하는 약한 자기장을 이용해 양자 이상 홀 효과에서 홀 저항 양자화 정확도 10 ppb를 달성해 강한 자기장 없이도 양자 저항 표준을 지향합니다. Cr–(Bi, Sb)–Te 기반 자기 헤테로구조 박막에서는 30 nA에서 홀 저항의 이론값 대비 편차를 2 ppm 미만으로 제시해 정밀 측정 기반을 강화합니다 (총 인용수: 131).</p></li>
<li><p><strong>NIST</strong>: 카고메 금속과 웨일 반금속에서 자기구조와 위상 수송 응답을 함께 규명하는 연구에 집중하고 있습니다 (RTA 2.35, 문헌 51건). YMn₆Sn₆에서 중성자 회절과 수송 측정을 결합해 복수의 자기 상을 규명하고, 변동에 의해 구동되는 메커니즘으로 큰 위상 홀 효과를 설명합니다. 같은 물질에서 면내 자기장 인가 시 약 240 K 부근에서 위상 홀 효과가 나타나는 장–온도 상도를 제시하고, 스커미온 격자 대신 c축 성분을 갖는 더블-팬 스핀 구조가 기여함을 중성자 회절로 연결합니다. NdAlSi에서는 중성자 회절과 양자 진동, 밀도 범함수 이론을 함께 사용해 웨일 페르미온과 연관된 장주기 나선형 자기질서와 그 기원을 제시합니다 (총 인용수: 158).</p></li>
<li><p><strong>KRISS</strong>: 시간분해 분광과 표면 민감 측정을 통해 자기 위상절연체·자성 웨일 상태의 표면 전자구조와 동역학을 규명하는 연구에 집중하고 있습니다 (RTA 1.52, 문헌 9건). MnBi₂Te₄에서 시간분해 광전자 분광법과 시간분해 자기광학 커 효과 측정을 결합해 표면과 벌크의 전자기 응답을 동역학으로 분리하고, 2차원 루더먼–키텔–카스야–요시다 상호작용 기반 모델이 표면 기원 교환 갭의 초기 소광을 인자 2 이내로 포착함을 제시합니다. 또한 [Gd₂C]²⁺·2e⁻ 강유전 일렉트라이드에서 ARPES로 웨일 원뿔과 페르미-아크 표면 상태를 확인하고, 최상층의 부유 전자에 의해 이중 적층 표면 상태가 형성됨을 제시합니다. Sb 도핑 Bi₂Se₃ 나노와이어에서는 열기전압으로 아하라노프–봄 진동의 위상 반전을 게이트 전압으로 제어하며, 위상 결맞음이 T = 15 K까지 유지됨을 제시합니다 (총 인용수: 5).</p></li>
</ul>
</section>
</section>
<section id="정책부합성분포" class="level2">
<h2 class="anchored" data-anchor-id="정책부합성분포">5. 정책부합성(분포)</h2>
<p>정책부합성은 문헌(제목+초록) 기반 분류 결과의 <strong>분포</strong>를 요약한 것으로, 본 간이 리포트에서는 ‘비율/건수’만을 제시합니다(인과·정당화 단정 금지).</p>
<section id="분포비율건수" class="level3">
<h3 class="anchored" data-anchor-id="분포비율건수">5-1. 분포(비율%/건수)</h3>
<table class="table">
<thead>
<tr class="header">
<th>정책 카테고리</th>
<th style="text-align: right;">비율(%)</th>
<th style="text-align: right;">건수(편)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>기후·환경 정책 지원 측정 과학</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>보건·보건안보 정책 지원 측정 과학</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>식품·물·소비자 안전 정책 지원 측정 과학</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>에너지 전환·에너지안보 정책 지원 측정 과학</td>
<td style="text-align: right;">12.90</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td>산업혁신·첨단제조 정책 지원 측정 과학</td>
<td style="text-align: right;">87.10</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="even">
<td>미분류</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">112</td>
</tr>
<tr class="odd">
<td>합계</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">31</td>
</tr>
<tr class="even">
<td>기준 문헌 수</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">143</td>
</tr>
</tbody>
</table>
</section>
<section id="정책부합성-해석" class="level3">
<h3 class="anchored" data-anchor-id="정책부합성-해석">5-2. 정책부합성 해석</h3>
<p>이 클러스터는 위상 양자물질의 전자 밴드 위상이 홀저항·종저항·자화·열전 신호·광응답 등 측정 가능한 전기·자기 응답으로 어떻게 나타나는지를 정량화하는 연구를 다루며, 문헌 분류 결과 <code>산업혁신·첨단제조 정책 지원 측정 과학</code> 영역이 87.10%(27편) 로 가장 높은 비중을 차지합니다. 이는 저온·고자장, 게이팅, 각도분해 광전자분광 등을 통해 전자구조 파라미터를 추출하고 소자 성능과 연결하는 내용이 포함되기 때문입니다.</p>
<p>구체적으로 <code>the performance of the p-Bi2Te3/n-Si heterostructure diode with different metallic contacts</code>처럼 위상 절연체 박막과 실리콘을 결합한 이종접합 다이오드에서 금속 접촉에 따른 전류-전압 특성과 지표를 비교·추출하는 접근은 소자 제작 조건과 성능 평가를 핵심으로 하여 산업혁신·첨단제조 정책 지원 측정 과학과 직접 맞닿습니다.</p>
<p>다만 이 결과는 문헌(제목+초록) 기반 분류와 복수 라벨 적용 여부에 따라 달라질 수 있으므로, 전체 기준 문헌 143편 대비 분류된 31편의 대표성과 세부 분류 기준을 함께 검토가 필요합니다.</p>
</section>
<section id="분류-근거-예시" class="level3">
<h3 class="anchored" data-anchor-id="분류-근거-예시">5-3. 분류 근거 예시</h3>
<p>형식: <code>연도 · 정책 분야 · 측정 축 · 제목</code> — 초록 발췌 (제목은 굵게, 발췌문은 이탤릭).- 2020 · 산업혁신·첨단제조 정책 지원 측정 과학 · Electricity and Magnetism(EM) · <strong>Effect of Different Metallic Contacts on the Device Performance of a p-n Heterostructure of a Topological Insulator and Silicon(p-Bi&lt; sub&gt;2&lt;/sub&gt;Te&lt;sub&gt;3&lt;/sub&gt;/n-Si)</strong> — <em>…ce microscopy(AFM; atomic force microscopy). The CV characterization for the diode showed almost no hysteresis except for the gold (Au) contact device, which could be due to the trapping of electrons at the interface. The current-voltage(IV) measurement was done in the dark, which confirmed the formation of p-n diode heterostructure. Diode having platinum (Pt) metallic contact…</em>- 2022 · 산업혁신·첨단제조 정책 지원 측정 과학 · Photometry and Radiometry(PR) · <strong>Investigation of RF sputtered, n-Bi2Se3 heterojunction on p-Si for enhanced NIR optoelectronic applications</strong> — <em>…bit. In this work RF magnetron sputtering technique was used to fabricate the high-quality n-Bi2Se3/p-Si heterojunction device. The structural properties of the grown Bi2Se3 thin films were examined by XRD, SEM, Raman and Energy dispersive spectroscopy. The current-voltage(I-V) characteristic revealed the development of effective p-n junction with a…</em></p>
<p>관련도 해석 메모: 특정 카테고리의 비율/건수가 높다는 것은 해당 축으로 분류된 문헌이 상대적으로 많음을 의미합니다. 다만 분류 기준·모호성·복수 라벨 여부에 따라 분포가 달라질 수 있어, 상세 리포팅에서는 클러스터 스코프(기술/응용) 와 함께 교차 검토하는 것이 안전합니다.</p>
</section>
</section>
<section id="요약" class="level2">
<h2 class="anchored" data-anchor-id="요약">6. 요약</h2>
<p>이 클러스터는 <strong>topological insulator</strong>, <strong>weyl semimetal</strong> 등 위상 양자물질에서 전자 밴드의 “위상”이 전기·자기·열전·광학 응답으로 어떻게 나타나는지를 정밀 측정으로 연결하는 연구를 다룹니다. 벌크와 <strong>surface</strong> 전도의 혼재, 결함·도핑·두께 등 공정 변수가 신호 해석을 흔드는 상황에서 홀저항·종저항, <strong>anomalous hall effect</strong>, <strong>field</strong> 인가 조건, 각도분해 광전자분광 등을 통해 전자구조(표면/벌크 상태) 와 위상 성질(예: 베리 곡률) 을 정량 파라미터로 정리하는 흐름입니다. 지표는 성장성 81.03, 파급력 94.87, 기술진보기여도 22.56, 스코프 다양성(폭) 12.31, 종합 80.51로 나타나며, 최근 5년 문헌 수는 1,665건이고 연도별로 2020년 271건, 2021년 314건, 2022년 385건, 2023년 344건, 2024년 351건으로 정리됩니다.</p>
<p>2020–2024년 비교에서 KRISS는 9건, RTA(revealed technological advantage) 1.52, Excellence10 0.00으로 나타나며, 같은 기간 NIST는 51건, RTA 2.35, Excellence10 23.53, NMIJ/AIST는 8건, RTA 3.07, Excellence10 25.00입니다. 이를 바탕으로 KRISS는 BIPM 비교군에서 문헌 수 기준 상위 3개 기관에 포함되며(상위 3개: NPLI 68건, NIST 51건, KRISS 9건), RTA 11.76로 1.00을 상회한다는 점이 수치로 확인됩니다. 다만 KRISS의 Excellence10 0.00은 표본 문헌 수(9건) 에 민감할 수 있어 참고 수준에서 함께 보아야 합니다. 협력 네트워크에서는 KRISS의 연결 수 25, 가중 연결 강도 165.00이며(51개 기관 중 34위), BIPM 한정(2020–2024) 에서는 연결 수 22, 가중 연결 강도 108.00으로 정리됩니다.</p>
<p>정책부합성 분포는 분류된 31건(기준 문헌 143건) 중 ‘산업혁신·첨단제조 정책 지원 측정 과학’이 87.10%(27건), ‘에너지 전환·에너지안보 정책 지원 측정 과학’이 12.90%(4건) 로 나타나 최상위 범주가 전자의 비중으로 도출된 것으로 관측됩니다. 최상위 범주 근거에는 전기·자기 및 광학 관련 측정 분류가 함께 제시되며(예: Electricity and Magnetism 13, Photometry and Radiometry 9), 소자 성능과 계면·접촉 조건에 따른 전기적 특성 평가 같은 내용이 포함됩니다. 이해를 돕는 예로 <code>p-Bi2Te3/n-Si heterostructure diode</code>와 같이 위상 물질 박막과 실리콘 기반 접합 소자에서 전류-전압 특성을 비교하는 사례가 제시됩니다. 또한 본 클러스터는 ‘역량 공백’ 유형으로, RTA 1.52와 문헌 수 9건은 기준을 충족하나 Excellence10 0.00이 기준(8.00) 에 미달하며, RTA ≥ 1.00 기관으로 NIST, NMIJ/AIST가 제시됩니다. 향후에는 KRISS 문헌 9건의 주제 범위가 <strong>anomalous hall effect</strong>, <strong>surface</strong>, <strong>field</strong> 등 핵심 키워드 축에서 어떻게 분포하는지와, Excellence10 0.00이 측정 환경·프로토콜 성격과 어떤 관계를 보이는지 등을 함께 검토할 수 있습니다.</p>
</section>
<section id="부록.-데이터-커버리지주의" class="level2">
<h2 class="anchored" data-anchor-id="부록.-데이터-커버리지주의">부록. 데이터 커버리지·주의</h2>
<ul>
<li>최근 5개년 KRISS 논문 수가 9편으로 작아, 비율/퍼센타일 해석은 보수적으로 보는 것이 안전합니다.</li>
<li>키워드 추이는 ‘문서 포함 비율(%)’ 지표이며, 논문 수 증가/감소로 단정하지 않습니다.</li>
<li>정책부합성은 문헌(제목+초록) 기반 분류 결과의 분포이며, 인과/정당화로 해석하지 않습니다.</li>
<li>10개 기관 성과 지표(4-1, 2020–2024) 는 선택된 10개 기관에 한정된 비교입니다(모든 기관 전체 비교 아님).</li>
</ul>
</section>
<section id="부록.-약어" class="level2">
<h2 class="anchored" data-anchor-id="부록.-약어">부록. 약어</h2>
<p>보고서 본문에 등장한 약어와 영문 전체 명칭을 정리했습니다(첫 등장에만 영문 전체 명칭을 포함하고, 이후는 약어만 사용).</p>
<table class="table">
<thead>
<tr class="header">
<th>약어</th>
<th>영문 전체 명칭</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AFM</td>
<td>atomic force microscopy</td>
</tr>
<tr class="even">
<td>RTA</td>
<td>revealed technological advantage</td>
</tr>
</tbody>
</table>
</section>
<section id="부록.-상위-인용-논문" class="level2">
<h2 class="anchored" data-anchor-id="부록.-상위-인용-논문">부록. 상위 인용 논문</h2>
<p>본 부록은 입력 데이터에서 제공되는 최소 서지(제목/연도/WoS UID/인용수)를 기준으로 정리했습니다.</p>
<section id="부록-1.-전체기간-인용수-상위-5개" class="level3">
<h3 class="anchored" data-anchor-id="부록-1.-전체기간-인용수-상위-5개">부록-1. 전체기간 인용수 상위 5개</h3>
<ol type="1">
<li>Topological insulators in Bi<sub>2</sub>Se<sub>3</sub>, Bi<sub>2</sub>Te<sub>3</sub> and Sb<sub>2</sub>Te<sub>3</sub> with a single Dirac cone on the surface. (2009). <em>Web of Science Core Collection</em> (UID: WOS:000266544800024; 인용수: 5,406).</li>
<li>Berry phase effects on electronic properties. (2010). <em>Web of Science Core Collection</em> (UID: WOS:000279557500001; 인용수: 3,937).</li>
<li>Anomalous Hall effect. (2010). <em>Web of Science Core Collection</em> (UID: WOS:000278228900001; 인용수: 3,690).</li>
<li>Experimental Realization of a Three-Dimensional Topological Insulator, Bi<sub>2</sub>Te<sub>3</sub>. (2009). <em>Web of Science Core Collection</em> (UID: WOS:000267802000040; 인용수: 3,167).</li>
<li>Experimental Observation of the Quantum Anomalous Hall Effect in a Magnetic Topological Insulator. (2013). <em>Web of Science Core Collection</em> (UID: WOS:000317341400047; 인용수: 3,114).</li>
</ol>
</section>
<section id="부록-2.-최근-5년20202024-인용수-상위-5개" class="level3">
<h3 class="anchored" data-anchor-id="부록-2.-최근-5년20202024-인용수-상위-5개">부록-2. 최근 5년(2020–2024) 인용수 상위 5개</h3>
<ol type="1">
<li>Quantum anomalous Hall effect in intrinsic magnetic topological insulator MnBi<sub>2</sub>Te<sub>4</sub>. (2020). <em>Web of Science Core Collection</em> (UID: WOS:000515235800040; 인용수: 1,248).</li>
<li>CsV<sub>3</sub>Sb<sub>5</sub>: A Z<sub>2</sub> Topological Kagome Metal with a Superconducting Ground State. (2020). <em>Web of Science Core Collection</em> (UID: WOS:000597151900015; 인용수: 680).</li>
<li>Robust axion insulator and Chern insulator phases in a two-dimensional antiferromagnetic topological insulator. (2020). <em>Web of Science Core Collection</em> (UID: WOS:000508170200002; 인용수: 655).</li>
<li>Dirac fermions and flat bands in the ideal kagome metal FeSn. (2020). <em>Web of Science Core Collection</em> (UID: WOS:000511169400011; 인용수: 484).</li>
<li>Superconductivity in the Z<sub>2</sub> kagome metal KV<sub>3</sub>Sb<sub>5</sub>. (2021). <em>Web of Science Core Collection</em> (UID: WOS:000627741900001; 인용수: 392).</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../docs/detailed_reports/cluster_179/report.html" class="pagination-link" aria-label="29-179 - 프로테오믹스 질량분석 (역량 공백)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">^</span>&nbsp; <span class="chapter-title">29-179 - 프로테오믹스 질량분석 (역량 공백)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../docs/detailed_reports/cluster_62/report.html" class="pagination-link" aria-label="32-62 - 집적 광주파수콤 (역량 공백)">
        <span class="nav-page-text"><span class="chapter-number">`</span>&nbsp; <span class="chapter-title">32-62 - 집적 광주파수콤 (역량 공백)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/KISTI-GlobalRnD/kriss-databook-2025/blob/main/docs/detailed_reports/cluster_169/report.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/KISTI-GlobalRnD/kriss-databook-2025/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"selector":".lightbox","openEffect":"zoom"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>