# 3-2) KRISS와 BIPM 주요 연구기관의 연구 포트폴리오 및 역량을 고려한 유망 연구영역 후보군 도출

여기서는 표준과학 연구 분야 문헌 클러스터링의 마이크로(micro)-레벨 클러스터(195개)에 대해 3-1에서 수행한 벤치마킹 기관과 KRISS의 연구프로파일 분석 결과를 바탕으로, KRISS의 연구 포트폴리오 구성 전략을 지원하기 위한 유망 연구영역 후보군을 유형화한다. KRISS의 현재 역량과 확장 가능성, 그리고 벤치마킹 기관들의 집중 영역을 함께 고려해 실행 가능한 포트폴리오 구성 시나리오를 제시하는 것을 목표로 한다. 우선 양적 역량을 갖추었는가의 기준은 최근 5년 기준으로 RTA가 1 이상이면서 동시에 최근 5년 기준 문헌수가 5편 이상(연평균 1편 이상)인지의 여부로, 질적 역량을 갖추었는가의 기준은 해당 연구영역에서 최근 5년 기준 엑셀런스 지수(상위 10% 문헌 비중)가 8 이상인지의 여부로 판정하였다.

첫 번째 시나리오는 KRISS가 이미 양적·질적으로 역량을 확보한 영역을 ‘핵심 역량 연구영역’으로 정의하고, 이를 유망 후보군 유형1으로 제시하는 방식이다. 이 후보군에 속하는 연구 영역들에서는 KRISS가 평균 이상의 특화(또는 집중)를 보이면서, 상위 10% 문헌 비중이 일정 수준 이상으로 확보되어 있고, 최소한의 산출 규모도 유지되는 경우만을 포함하고 있다. 이 조건을 만족하는 영역은 총 25개이며, 이 유형의 후보군에 포함된 연구영역은 아래 표와 같다.

|                                                |           |                          |                    |
|------------------------------------------------|-----------|--------------------------|--------------------|
| \[표 \] KRISS 핵심 역량 연구영역(후보군 유형1) |           |                          |                    |
| 연구영역(Meso-Micro)                           | KRISS RTA | KRISS Excellence 10 지수 | KRISS 5개년 문헌수 |
| 0-72 - 방사선치료 선량표준                     | 1.87      | 9.52                     | 21                 |
| 1-142 - PM2.5·오존 측정 및 추세                | 1.01      | 9.09                     | 22                 |
| 8-11 - 비풀러렌 유기태양전지                   | 1.71      | 8.33                     | 24                 |
| 9-12 - 배터리 양극·계면 측정                   | 2.69      | 10.00                    | 20                 |
| 9-52 - 데이터기반 소재발견                     | 1.66      | 8.33                     | 24                 |
| 10-14 - 산화물 결함 측정·제어                  | 2.77      | 16.67                    | 12                 |
| 10-173 - 2차원·산화물 가스센서                 | 1.65      | 10.00                    | 20                 |
| 11-158 - 그래핀 산화물·양자점 소재             | 1.15      | 14.29                    | 14                 |
| 11-24 - 폴리머 난연성 측정                     | 2.21      | 8.11                     | 37                 |
| 12-165 - 자성 스키르미온 계측                  | 2.82      | 12.50                    | 16                 |
| 12-167 - 스핀전류 변환·제어                    | 2.36      | 21.62                    | 37                 |
| 17-27 - 수소취성 파괴 측정                     | 7.29      | 14.29                    | 35                 |
| 20-124 - 광자 양자정보기술                     | 1.28      | 11.11                    | 18                 |
| 20-182 - 다이아몬드결함양자센서                | 1.79      | 28.57                    | 7                  |
| 21-74 - XFEL 초고속 계측                       | 1.76      | 10.00                    | 10                 |
| 22-34 - 나노와이어·질화물 소자                 | 2.56      | 11.11                    | 9                  |
| 29-104 - 분석법 검증·표준화                    | 7.33      | 15.16                    | 46                 |
| 30-60 - 열전재료 성능지수 측정                 | 1.09      | 12.92                    | 13                 |
| 33-64 - 저온 플라즈마 계측                     | 6.88      | 13.73                    | 38                 |
| 34-69 - 메타표면 광학소자                      | 3.08      | 19.23                    | 52                 |
| 36-77 - 2차원 광전소자 측정                    | 4.13      | 8.20                     | 61                 |
| 37-145 - 광음향·초음파 나노진단치료            | 1.17      | 10.02                    | 10                 |
| 41-127 - 뇌파 감정상태 측정                    | 1.16      | 57.14                    | 14                 |
| 43-178 - 현장진단 바이오센서                   | 1.04      | 16.37                    | 12                 |
| 45-151 - 배열 신호처리 측정                    | 1.13      | 28.57                    | 7                  |

두 번째 시나리오는 후보군 유형1로 도출된 25개 핵심 역량 연구영역을 기반으로, 인지적 유사성이 높은 인접 연구영역으로 포트폴리오를 확장하는 전략을 가정한다. 이를 유망 후보군 유형2인 ‘확장 가능 연구영역’으로 정의한다. 이때 유형2는 “KRISS가 현재 역량을 갖추었다고 볼 수는 없지만, 유형1의 핵심 역량과 지식 기반이 유사하여 기존 역량을 바탕으로 접근 가능한 영역”을 체계적으로 선별하는 데 목적이 있다.

구체적으로는 먼저 유형1의 25개 영역에서 각 영역 문헌들의 기반 문헌의 인지적 유사도(cognitive similarity)가 0.4 이상인 연구영역을 확장 후보로 설정한다. 이후 확장 후보 가운데서, 앞서 정의한 양적 역량 기준과 질적 역량 기준을 동시에 충족하지 못한 영역만을 유형2에 포함한다. 다시 말해 유형2는 핵심 역량(유형1)과 유사도 기준으로 연결되지만, 양적 역량 또는 질적 역량 중 하나 이상이 아직 충분히 확보되지 않은 영역으로 구성된다. 이 방식은 KRISS가 이미 강점을 가진 축과의 근접성을 활용해 연구 포트폴리오를 확장가능한 영역을 선별적으로 관리하기 위한 기준으로 설계되었다. 유형2 후보군은 총 56개이며, 이 유형의 후보군에 포함된 연구영역은 아래 표와 같다.

<table>
<colgroup>
<col style="width: 51%" />
<col style="width: 48%" />
</colgroup>
<tbody>
<tr class="odd">
<td colspan="2">[표 ] KRISS 확장 가능 연구영역(후보군 유형2)</td>
</tr>
<tr class="even">
<td>연구영역(Meso-Micro)</td>
<td>기반이 되는 유형1 연구영역, 인지적 유사도</td>
</tr>
<tr class="odd">
<td>1-1 - 에어로졸·POPs 측정표준</td>
<td>1-142 - PM2.5·오존 측정 및 추세, 0.904</td>
</tr>
<tr class="even">
<td>2-117 - 레이저 미량가스 분광측정</td>
<td><p>9-52 - 데이터기반 소재발견, 0.687;</p>
<p>21-74 - XFEL 초고속 계측, 0.58</p></td>
</tr>
<tr class="odd">
<td>2-2 - 분자 분광 선목록</td>
<td><p>9-52 - 데이터기반 소재발견, 0.68;</p>
<p>21-74 - XFEL 초고속 계측, 0.576</p></td>
</tr>
<tr class="even">
<td>2-67 - 분자 열화학·분광 계산</td>
<td><p>9-52 - 데이터기반 소재발견, 0.691;</p>
<p>21-74 - XFEL 초고속 계측, 0.577</p></td>
</tr>
<tr class="odd">
<td>3-4 - 나노압입 역학 측정</td>
<td>17-27 - 수소취성 파괴 측정, 0.873</td>
</tr>
<tr class="even">
<td>3-65 - DLC·질화물 경질코팅</td>
<td>20-182 - 다이아몬드결함양자센서, 0.982</td>
</tr>
<tr class="odd">
<td>7-154 - 리튬이온전지 예지진단</td>
<td>9-12 - 배터리 양극·계면 측정, 0.997</td>
</tr>
<tr class="even">
<td>8-144 - 콜로이드 양자점 광전소자</td>
<td>37-145 - 광음향·초음파 나노진단치료, 0.631</td>
</tr>
<tr class="odd">
<td>8-163 - 케스터라이트·Sb₂Se₃ 박막 태양전지</td>
<td>30-60 - 열전재료 성능지수 측정, 0.998</td>
</tr>
<tr class="even">
<td>9-191 - 물분해 전기촉매 측정</td>
<td>9-12 - 배터리 양극·계면 측정, 0.998</td>
</tr>
<tr class="odd">
<td>11-15 - 전자파 차폐·흡수 복합재</td>
<td>34-69 - 메타표면 광학소자, 0.852</td>
</tr>
<tr class="even">
<td>11-80 - 그래핀·CNT 복합재 계면</td>
<td>36-77 - 2차원 광전소자 측정, 0.878</td>
</tr>
<tr class="odd">
<td>12-138 - 수직자기터널접합</td>
<td><p>12-165 - 자성 스키르미온 계측, 0.998;</p>
<p>12-167 - 스핀전류 변환·제어, 0.978</p></td>
</tr>
<tr class="even">
<td>12-16 - 교환바이어스 계면자성</td>
<td><p>12-165 - 자성 스키르미온 계측, 0.997;</p>
<p>12-167 - 스핀전류 변환·제어, 0.974</p></td>
</tr>
<tr class="odd">
<td>12-63 - 자구벽 동역학 측정</td>
<td><p>12-165 - 자성 스키르미온 계측, 0.943;</p>
<p>12-167 - 스핀전류 변환·제어, 0.924</p></td>
</tr>
<tr class="even">
<td>12-96 - 스핀토크 나노발진기</td>
<td><p>12-165 - 자성 스키르미온 계측, 0.998;</p>
<p>12-167 - 스핀전류 변환·제어, 0.974</p></td>
</tr>
<tr class="odd">
<td>13-17 - 연자성재료 손실·센싱</td>
<td><p>12-165 - 자성 스키르미온 계측, 0.992;</p>
<p>12-167 - 스핀전류 변환·제어, 0.968</p></td>
</tr>
<tr class="even">
<td>13-66 - 전류·자기장 측정센서</td>
<td><p>12-165 - 자성 스키르미온 계측, 0.626;</p>
<p>12-167 - 스핀전류 변환·제어, 0.62</p></td>
</tr>
<tr class="odd">
<td>14-57 - 자기열량 재료</td>
<td><p>12-165 - 자성 스키르미온 계측, 0.988;</p>
<p>12-167 - 스핀전류 변환·제어, 0.967</p></td>
</tr>
<tr class="even">
<td>17-143 - 초합금 상평형·확산 설계</td>
<td>17-27 - 수소취성 파괴 측정, 0.959</td>
</tr>
<tr class="odd">
<td>17-47 - 금속 적층제조 계측</td>
<td>17-27 - 수소취성 파괴 측정, 0.754</td>
</tr>
<tr class="even">
<td>18-28 - 소각산란 구조측정</td>
<td>11-24 - 폴리머 난연성 측정, 0.781</td>
</tr>
<tr class="odd">
<td>19-118 - 테라헤르츠 계측</td>
<td>34-69 - 메타표면 광학소자, 0.891</td>
</tr>
<tr class="even">
<td>19-129 - 마이크로파 유전특성 측정</td>
<td>34-69 - 메타표면 광학소자, 0.755</td>
</tr>
<tr class="odd">
<td>19-29 - 밀리·테라파 채널측정</td>
<td>34-69 - 메타표면 광학소자, 0.866</td>
</tr>
<tr class="even">
<td>20-103 - 양자광 메모리</td>
<td>20-124 - 광자 양자정보기술, 0.993</td>
</tr>
<tr class="odd">
<td>20-156 - 광기계 양자측정</td>
<td>20-124 - 광자 양자정보기술, 0.887</td>
</tr>
<tr class="even">
<td>20-32 - 양자점 단일광자원</td>
<td>22-34 - 나노와이어·질화물 소자, 0.719</td>
</tr>
<tr class="odd">
<td>20-71 - 양자 비국소성 검증</td>
<td>20-124 - 광자 양자정보기술, 0.98</td>
</tr>
<tr class="even">
<td>20-76 - 광펌핑 자력계</td>
<td>20-124 - 광자 양자정보기술, 0.861</td>
</tr>
<tr class="odd">
<td>21-147 - 레이저 플라즈마 가속</td>
<td>21-74 - XFEL 초고속 계측, 0.809</td>
</tr>
<tr class="even">
<td>21-54 - 아토초 펄스 계측</td>
<td>21-74 - XFEL 초고속 계측, 0.846</td>
</tr>
<tr class="odd">
<td>22-122 - 탄소나노튜브 계측</td>
<td>36-77 - 2차원 광전소자 측정, 0.962</td>
</tr>
<tr class="even">
<td>22-36 - 실리콘 나노광전소자</td>
<td><p>22-34 - 나노와이어·질화물 소자, 0.699;</p>
<p>9-52 - 데이터기반 소재발견, 0.572</p></td>
</tr>
<tr class="odd">
<td>25-109 - 페시바흐 페르미 초유체</td>
<td>20-124 - 광자 양자정보기술, 0.996</td>
</tr>
<tr class="even">
<td>25-123 - 위상광자·비에르미트상</td>
<td>20-124 - 광자 양자정보기술, 0.846</td>
</tr>
<tr class="odd">
<td>25-176 - 양자다체 비평형 동역학</td>
<td>20-124 - 광자 양자정보기술, 0.985</td>
</tr>
<tr class="even">
<td>25-43 - 초저온 극성분자</td>
<td>20-124 - 광자 양자정보기술, 0.982</td>
</tr>
<tr class="odd">
<td>25-48 - 보스응축체 비선형 여기</td>
<td>20-124 - 광자 양자정보기술, 0.982</td>
</tr>
<tr class="even">
<td>25-83 - 광격자 초저온 원자</td>
<td>20-124 - 광자 양자정보기술, 0.968</td>
</tr>
<tr class="odd">
<td>28-55 - 플라즈몬 라만증강 분광</td>
<td>37-145 - 광음향·초음파 나노진단치료, 0.572</td>
</tr>
<tr class="even">
<td>31-120 - 레이저 플라즈마 원소분광</td>
<td>21-74 - XFEL 초고속 계측, 0.789</td>
</tr>
<tr class="odd">
<td>31-61 - 초소수성 표면 레이저 가공</td>
<td>21-74 - XFEL 초고속 계측, 0.721</td>
</tr>
<tr class="even">
<td>32-87 - 광주파수빗 계측</td>
<td>21-74 - XFEL 초고속 계측, 0.42</td>
</tr>
<tr class="odd">
<td>34-185 - 테라헤르츠 메타물질 측정</td>
<td>34-69 - 메타표면 광학소자, 0.911</td>
</tr>
<tr class="even">
<td>35-94 - 연료전지 수분 계측</td>
<td>9-12 - 배터리 양극·계면 측정, 0.716</td>
</tr>
<tr class="odd">
<td>36-135 - 그래핀 합성·물성 측정</td>
<td>36-77 - 2차원 광전소자 측정, 0.947</td>
</tr>
<tr class="even">
<td>37-174 - 자기나노입자 측정·표준</td>
<td>37-145 - 광음향·초음파 나노진단치료, 0.651</td>
</tr>
<tr class="odd">
<td>37-79 - 미세·나노입자 계측표준</td>
<td>37-145 - 광음향·초음파 나노진단치료, 0.607</td>
</tr>
<tr class="even">
<td>38-107 - 초전도 회로 양자전기역학</td>
<td>20-124 - 광자 양자정보기술, 0.874</td>
</tr>
<tr class="odd">
<td>38-84 - 양자알고리즘·오류정정</td>
<td>20-124 - 광자 양자정보기술, 0.996</td>
</tr>
<tr class="even">
<td>40-108 - 양성자 반지름 정밀측정</td>
<td><p>9-52 - 데이터기반 소재발견, 0.64;</p>
<p>21-74 - XFEL 초고속 계측, 0.563</p></td>
</tr>
<tr class="odd">
<td>40-119 - 원자·이온 양자측정</td>
<td>20-124 - 광자 양자정보기술, 0.979</td>
</tr>
<tr class="even">
<td>40-88 - EUV/X선 원자분광</td>
<td><p>9-52 - 데이터기반 소재발견, 0.683;</p>
<p>21-74 - XFEL 초고속 계측, 0.643</p></td>
</tr>
<tr class="odd">
<td>41-141 - 신축성 전자피부 센서</td>
<td>8-11 - 비풀러렌 유기태양전지, 0.812</td>
</tr>
<tr class="even">
<td>45-136 - 시변주파수 정밀분석</td>
<td>45-151 - 배열 신호처리 측정, 0.409</td>
</tr>
</tbody>
</table>

세 번째 시나리오는 KRISS의 공백 영역을 중심으로 유망 후보를 설정하는 접근이다. 이를 유망 후보군 유형3인 ‘역량 공백 연구영역’으로 정의하며, 유형1(핵심 역량 연구영역)과 유형2(확장 가능 연구영역)에 포함되지 않은 영역 가운데서 벤치마킹 기관들이 공통적으로 역량을 보유한 영역을 우선적으로 식별한다. 여기서 ‘공백’은 단순히 KRISS의 성과가 낮다는 의미가 아니라, KRISS의 현재 포트폴리오 구조상 핵심 역량으로도, 인접 확장 후보로도 분류되지 않은 영역임에도 불구하고 외부 주요 기관에서는 이미 역량이 축적된 영역을 의미한다.

구체적으로 유형3은 “유형1 또는 유형2에 속하지 않으면서”, 동시에 “벤치마킹 기관 중 2개 이상이 양적 역량 기준과 질적 역량 기준을 모두 충족하는 연구영역으로 정의한다. 즉, 외부에서는 다수 기관이 해당 영역에서 충분한 산출 규모와 상위권 성과를 동시에 확보하고 있는 반면, KRISS는 아직 포트폴리오로 편입하지 못했거나 역량이 충분히 축적되지 않은 영역을 체계적으로 추려내는 구조다. 유형3 후보군은 총 20개이며, 이 유형의 후보군에 포함된 연구영역은 아래 표와 같다.

|                                                |                           |
|------------------------------------------------|---------------------------|
| \[표 \] KRISS 역량 공백 연구영역(후보군 유형3) |                           |
| 연구영역(Meso-Micro)                           | 역량을 갖춘 벤치마킹 기관 |
| 2-3 - 이온성액체 열물성                        | NIST; NPL; NPLI; NRC; PTB |
| 2-7 - 암모니아 연소 반응속도론                 | BAM; NRC; PTB             |
| 3-73 - 나노힘·마찰 정량측정                    | INRIM; NIST; NPL          |
| 9-189 - 다공성골격 가스분리                    | BAM; NIM; NIST            |
| 11-159 - 나노셀룰로오스 소재측정               | BAM; NIST; NPLI           |
| 15-112 - 업컨버전 나노입자                     | BAM; INRIM; NPL           |
| 18-133 - 적층 바이오제조 측정                  | BAM; INRIM; NRC; PTB      |
| 26-130 - CMB 편광·파워스펙트럼 측정            | NIST; NPL; NRC            |
| 26-131 - 중력파 검출·분석                      | INRIM; NMIJ/AIST          |
| 26-152 - 외계행성 검출·특성 측정               | NIST; NRC                 |
| 26-166 - 자화강착원반 난류·제트                | NIST; NRC                 |
| 29-179 - 프로테오믹스 질량분석                 | BAM; NIST; NRC            |
| 29-58 - 메타분석 방법론                        | NIM; NIST; NRC            |
| 29-89 - 대사체·지질체 측정표준                 | NIST; NPL; NRC            |
| 29-95 - 동위원소비 측정표준                    | NIM; NIST; NPL; NRC       |
| 30-169 - 위상 양자물질 전자구조 측정           | NIST; NMIJ/AIST           |
| 32-62 - 집적 광주파수콤                        | NIST; NPL; NRC            |
| 34-162 - 궤도각운동량 광계측                   | NIM; NIST; PTB            |
| 43-125 - 유전체 변이 측정표준                  | BAM; NIM; NIST            |

요약하면, 유형1은 KRISS가 이미 양적·질적 역량을 동시에 확보한 영역으로 구성된 핵심 역량 보유 후보군이고, 유형2는 유형1과 인지적으로 가까우나 양적 또는 질적 역량이 아직 충분히 확보되지 않은 인접 확장 가능 후보군이며, 유형3은 KRISS의 포트폴리오와 역량을 고려할 때 공백 영역이지만 벤치마킹 기관 다수가 이미 역량을 확보한 영역으로 구성되어 전략적 도전이 필요한 후보군이다. 이후 단계에서는 이 세 유형 후보군을 대상으로 과학계량지표 기반 유망성 분석을 수행하고, 유형별로 유망성이 높은 상위 연구영역을 중심으로 최종 유망 연구영역을 도출한다.

